<?php
$Menu = array (
array('Title' => 'Two For Twenty',
    'ImageLoc' => './img/maincat/2for20.jpg',
    'Link' => './?category=twofor',
        array('Title' => 'Appetizers',
            'ImageLoc' => './img/twofor/app/mozzarella_sticks.jpg',
            'Link' => './page.php',
        array('Title' => 'Mozzarella Sticks',
            'ImageLoc' => './img/twofor/app/mozzarella_sticks.jpg'),
        array('Title' => 'Crunchy Onion Rings',
            'ImageLoc' => './img/twofor/app/onion_rings.jpg'),
        array('Title' => 'Two Side Salads(House or Caesar)',
            'ImageLoc' => './img/twofor/app/caesar_salad.jpg')),
array('Title' => 'Entrees',
    'ImageLoc' => 'llama',
        array('Title' => 'Three-Cheese Chicken Penne', 'ImageLoc' => 'llama'),
        array('Title' => 'Chicken Tenders Basket', 'ImageLoc' => 'llama'),
        array('Title' => 'The American Standard', 'ImageLoc' => 'llama'))
),
array('Title' => 'Better For You',
    'ImageLoc' => 'llama',
        array('Title' => 'The Smarter Choice',
        'ImageLoc' => 'llama',
        array('Title' => 'Hot Shot Whiskey Chicken', 'ImageLoc' => 'llama'),
        array('Title' => 'Savory Cedar Salmon', 'ImageLoc' => 'llama'),
        array('Title' => 'Shrimp Wonton Stir-Fry', 'ImageLoc' => 'llama'))
),
    array('Title' => 'Beverages',
        'ImageLoc' => 'llama',
        'Link' => '',
            array('Title' => 'Beers',
                'ImageLoc' => 'llama',
                'Link'=>'',
                array('Title' => 'Neighborhood Favorites',
                    'ImageLoc' => 'llama',
                    'Link' => ''
                ),
            array('Title' => 'Wines',
                'ImageLoc' => 'llama',
                'Link' => '')
),
        array('Title' => 'Refreshments',
            'ImageLoc' => 'llama',
            'Link' => '',
            array( 'Title' => 'Tea',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Lemonaid',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Lime-aids',
                'ImageLoc' => 'llama',
                'Link' => '')
)
    ),
        array('Title' => 'Burgers',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => 'Mushroom',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'American',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'TripleBacon',
                'ImageLoc' => 'llama',
                'Link' => '')),
    array('Title' => 'Desserts',
        'ImageLoc' => 'llama',
        'Link' => '',
            array('Title' => 'TripleChoc',
            'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'MapleBlonde',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'AppleCheeseCake',
                'ImageLoc' => 'llama',
                'Link' => '')
),
     array('Title' => 'MainEntrees',
         'ImageLoc' => 'llama',
         'Link' => '',
            array('Title' => 'Steak',
                'ImageLoc' => 'llama',
                'Link' => '',
                    array('Title' => 'GrilledOnionSirloin',
                        'ImageLoc' => 'llama',
                        'Link' => ''),
                    array('Title' => 'Sirloin',
                        'ImageLoc' => 'llama',
                        'Link' => ''),
                    array('Title' => 'PepperSirloin',
                        'ImageLoc' => 'llama',
                        'Link' => '')),
            array('Title' => 'Ribs',
                'ImageLoc' => 'llama',
                'Link' => '',
                    array('Title' => 'Riblets',
                        'ImageLoc' => 'llama',
                        'Link' => ''),
                    array('Title' => 'BabyBack',
                        'ImageLoc' => 'llama',
                        'Link' => '')),
            array('Title' => 'Chicken',
                'ImageLoc' => 'llama',
                'Link' => '',
                    array('Title' => 'BrewHouse',
                        'ImageLoc' => 'llama',
                        'Link' => ''),
                    array('Title' => 'BurbonChicken',
                        'ImageLoc' => 'llama',
                        'Link' => ''),
                    array('Title' => 'ChickenTend',
                        'ImageLoc' => 'llama',
                        'Link' => '')),
),

array('Title' => 'Lunch Combos',
   'ImageLoc' => 'llama',
   'Link' => '',
    array('Title' => 'Tomato Basil Soup +  French Onion Soup',
       'ImageLoc' => 'llama',
       'Link' => ''),
    array('Title' => 'House Salad(contains bacon) + Clubhouse Grille',
       'ImageLoc' => 'llama',
       'Link' => ''),
     array('Title' => 'Chicken Fajita Rollup + Shrimp Scampi Linguine',
       'ImageLoc' => 'llama',
       'Link' => '')),

    array('Title' => 'Salads',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'ThaiShrimp',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'FiestaChicken',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'ChickenCeasar',
            'ImageLoc' => 'llama',
            'Link' => '')
    ),
    array('Title' => 'PubDiet',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'ShrimpWonton',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'SirloinStout',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'CedarChicken',
            'ImageLoc' => 'llama',
            'Link' => '')
    ),
    array('Title' => 'Handhelds',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'New Triple Hog Dare Ya',
            'ImageLoc' => 'triple_hog_dare_ya.jpg',
            'Link' => ''),
        array('Title' => 'New Kickin Turkey Stacker',
            'ImageLoc' => 'turkey_stacker.jpg',
            'Link' => ''),
        array('Title' => 'American BLT',
            'ImageLoc' => 'blt.jpg',
            'Link' => '')),
    array('title' => 'Kids',
        'ImageLoc' => './images/kid1.jpg',
        'Link' => './?category=kids',
        array('Title' => 'Kid1',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'Kid2',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'Kid3',
            'ImageLoc' => 'llama',
            'Link' => ''))
);
echo "hello";
?>