<?php
$Menu = array (
    array('Title' => 'Two For Twenty',
        'ImageLoc' => './imgages/2for20.jpg',
        'Link' => './?category=twofor',
        array('Title' => 'Appetizers',
            'ImageLoc' => './img/twofor/mozzeralla_sticks.jpg',
            'Link' => './page.php',
            array('Title' => 'Mozzarella Sticks',
                'ImageLoc' => './img/twofor/mozzeralla_sticks.jpg'),
            array('Title' => 'Crunchy Onion Rings',
                'ImageLoc' => './img/twofor/onion_rings.jpg'),
            array('Title' => 'Two Side Salads(House or Caesar)',
                'ImageLoc' => './img/twofor/app/caesar_salad.jpg')),
        array('Title' => 'Entrees',
            'ImageLoc' => 'llama',
            array('Title' => 'Three-Cheese Chicken Penne', 'ImageLoc' => 'llama'),
            array('Title' => 'Chicken Tenders Basket', 'ImageLoc' => 'llama'),
            array('Title' => 'The American Standard', 'ImageLoc' => 'llama'))
    ),
    array('Title' => 'Better For You',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'The Smarter Choice',
            'ImageLoc' => 'llama',
            array('Title' => 'Hot Shot Whiskey Chicken', 'ImageLoc' => 'llama'),
            array('Title' => 'Savory Cedar Salmon', 'ImageLoc' => 'llama'),
            array('Title' => 'Shrimp Wonton Stir-Fry', 'ImageLoc' => 'llama'))
    ),
    array('Title' => 'Beverages',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'Beers',
            'ImageLoc' => 'llama',
            'Link'=>'',
            array('Title' => 'Neighborhood Favorites',
                'ImageLoc' => 'llama'
            )),
        array('Title' => 'Wines',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'Refreshments',
            'ImageLoc' => 'llama',
            'Link' => '',
            array( 'Title' => 'Tea',
                'ImageLoc' => 'llama'),
            array('Title' => 'Lemonade',
                'ImageLoc' => 'llama'),
            array('Title' => 'Limeade',
                'ImageLoc' => 'llama'))
    ),
    array('Title' => 'Handcrafted Burgers',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'All-In Burgers',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => 'Mushroom Swiss',
                'ImageLoc' => 'llama'),
            array('Title' => 'The American Standard',
                'ImageLoc' => 'llama'),
            array('Title' => 'Triple Bacon Burger',
                'ImageLoc' => 'llama')),
        array('Title' => 'Neighborhood Burgers',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => 'Cowboy Burger',
                'ImageLoc' => 'llama'),
            array('Title' => 'Quesadilla Burger',
                'ImageLoc' => 'llama'),
            array('Title' => 'The Classic',
                'ImageLoc' => 'llama'))
        ),
    array('Title' => 'Desserts',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'Triple Chocolate Meltdown',
        'ImageLoc' => 'llama'),
        array('Title' => 'Butter Pecan Blondie',
            'ImageLoc' => 'llama'),
        array('Title' => 'Apple Chimi-Cheesecake',
            'ImageLoc' => 'llama')
    ),
    array('Title' => 'Main Entrees',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'Steaks',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => '7oz Grilled Onion Sirloin with Stout Gravy',
                'ImageLoc' => 'llama'),
            array('Title' => '9oz House Sirloin',
                'ImageLoc' => 'llama'),
            array('Title' => 'Pepper-Crusted Sirloin & Whole Grains',
                'ImageLoc' => 'llama')),
        array('Title' => 'Ribs',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => 'Applebee\'s Riblets',
                'ImageLoc' => 'llama'),
            array('Title' => 'BabyBack',
                'ImageLoc' => 'llama')),
        array('Title' => 'Chicken',
            'ImageLoc' => 'llama',
            'Link' => '',
                array('Title' => 'BrewHouse',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'BurbonChicken',
                    'ImageLoc' => 'llama',
                    'Link' => ''),
                array('Title' => 'ChickenTend',
                    'ImageLoc' => 'llama',
                    'Link' => '')),
    ),
//Lunch Combo to Pub Diet
        array('Title' => 'Handhelds',
            'ImageLoc' => 'llama',
            'Link' => '',
            array('Title' => 'New Triple Hog Dare Ya',
                'ImageLoc' => 'triple_hog_dare_ya.jpg',
                'Link' => ''),
            array('Title' => 'New Kickin Turkey Stacker',
                'ImageLoc' => 'turkey_stacker.jpg',
                'Link' => ''),
            array('Title' => 'American BLT',
                'ImageLoc' => 'blt.jpg',
                'Link' => '')),
        array('title' => 'Kids',
            'ImageLoc' => './images/kid1.jpg',
            'Link' => './?category=kids',
            array('Title' => 'Kid1',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Kid2',
                'ImageLoc' => 'llama',
                'Link' => ''),
            array('Title' => 'Kid3',
                'ImageLoc' => 'llama',
                'Link' => ''))
    );
?>